name: prueba
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  connectivity_plus: ^6.1.2
  carousel_slider: ^4.2.1
  intl: ^0.18.0

  cupertino_icons: ^1.0.8
  logging: ^1.3.0

  hive: ^2.0.4
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

  hive_generator: ^2.0.1
  build_runner: ^2.4.6

  flutter_native_splash: ^2.3.2
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/portada.png
    - assets/images/fondo.png
    - assets/images/icono.png

  fonts:
    - family: Weigl
      fonts:
        - asset: assets/fonts/Weigl.ttf

# 🔹 Configuración de Splash Screen
flutter_native_splash:
  color: "#000000" #
  image: assets/images/fondo.png #
  fullscreen: true
  android_12:
    image: assets/images/fondo.png
    icon_background_color: "#000000"

# 🔹 Configuración de Icono de Aplicación
flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/icono.png" #
  adaptive_icon_background: "#000000" #
  adaptive_icon_foreground: "assets/images/icono.png"
